### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by pavazmo** [VandeurenGlenn/xlsx-converter#3]
Hi all,

When I'm running my simple node script , I get this error message.

My code:

```
const {convert} = require('xlsx-converter');
 
convert('agencios.xlsx',{ to: 'json' },{ write: 'out.json' }  ).then(result => {
  // do something with the result 
  console.log(result);
});

```
Error message:
```

const {convert} = require('xlsx-converter');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

```
I guess it's about the way of declare the constant, but i don't know why. Any lead?
Thank you.

**Comment by VandeurenGlenn** [comment]
Hi @pavazmo I missed you're issue somehow and you probably figured it out already by yourself.
If not, following should work.

```js
const xlsx = require('xlsx-converter');
const convert = xlsx.convert;
....
```
Or update your [nodejs](https://nodejs.org/en/) version.
